// AUTO-GENERATED FILE
// DO NOT EDIT MANUALLY!
// Generated by: Tools -> Generate ResourcePaths

namespace PlatformCore.Services.Factory
{
	public static class ResourcePaths
	{
		public static class GameAnalytics
		{
			public const string Settings = "GameAnalytics/Settings";
		}

		public static class Images
		{
			public const string TrainArriving = "Images/TrainArriving";
			public const string TrainLeaving = "Images/TrainLeaving";
		}

		public static class Items
		{
			public const string DicePrefab = "Items/DicePrefab";
			public const string ExtraDiceCapItem = "Items/ExtraDiceCapItem";
			public const string ItemBase = "Items/ItemBase";
			public const string ModifierSilencerItem = "Items/ModifierSilencerItem";
			public const string PassMultiplierItem = "Items/PassMultiplierItem";
			public const string RerollSelectedItem = "Items/RerollSelectedItem";
			public const string StepUpItem = "Items/StepUpItem";
		}

		public static class Json
		{
			public const string dice_game_modifiers_schedule = "Json/dice_game_modifiers_schedule";
			public const string dice_game_rules = "Json/dice_game_rules";
			public const string dice_types = "Json/dice_types";
			public const string enemy_ai_scenario_schedule = "Json/enemy_ai_scenario_schedule";
			public const string enemy_ai_scenarios = "Json/enemy_ai_scenarios";
			public const string items_catalog = "Json/items_catalog";
			public const string modifiers_ui = "Json/modifiers_ui";
			public const string player = "Json/player";
			public const string run_rules = "Json/run_rules";
			public const string shop = "Json/shop";
			public const string stations = "Json/stations";
			public const string texts_eng = "Json/texts_eng";
			public const string texts_ru = "Json/texts_ru";
		}

		public static class Player
		{
			public const string CinemachineCamera = "Player/CinemachineCamera";
			public const string NpcBase = "Player/NpcBase";
			public const string NpcConductor = "Player/NpcConductor";
			public const string NpcEnemy = "Player/NpcEnemy";
			public const string NpcPassenger = "Player/NpcPassenger";
			public const string NpcShopKeeper = "Player/NpcShopKeeper";
			public const string PlayerBase = "Player/PlayerBase";
			public const string PlayerInventory = "Player/PlayerInventory";
		}

		public static class Root
		{
			public const string ComboUpgradesConfig = "ComboUpgradesConfig";
			public const string DiceScoringConfig = "DiceScoringConfig";
			public const string DOTweenSettings = "DOTweenSettings";
		}

		public static class Shop
		{
			public const string ShopItemDice = "Shop/ShopItemDice";
			public const string TradeItem = "Shop/TradeItem";
		}

		public static class UI
		{
			public const string ColorStyleLibrary = "UI/ColorStyleLibrary";
			public const string ElementBackground = "UI/ElementBackground";
			public const string TextStyleLibrary = "UI/TextStyleLibrary";
			public const string DefaultTMP = "UI/TMP/DefaultTMP";
			public const string DescriptionTMP = "UI/TMP/DescriptionTMP";
			public const string HeaderTMP = "UI/TMP/HeaderTMP";
			public const string TextsVerticalSizebable = "UI/TMP/TextsVerticalSizebable";
			public const string UICursorView = "UI/UICursorView";
			public const string UIDiceUpgradeVariantView = "UI/UIDiceUpgradeVariantView";
			public const string UIDiceUpgradeView = "UI/UIDiceUpgradeView";
			public const string UIEndView = "UI/UIEndView";
			public const string UIGlobalNotificationView = "UI/UIGlobalNotificationView";
			public const string UIHintView = "UI/UIHintView";
			public const string UIMainMenu = "UI/UIMainMenu";
			public const string UIModifierDarkViewVariant = "UI/UIModifierDarkView Variant";
			public const string UIModifiersView = "UI/UIModifiersView";
			public const string UIModifierView = "UI/UIModifierView";
			public const string UINotificationsView = "UI/UINotificationsView";
			public const string UINotificationView = "UI/UINotificationView";
			public const string UIPlayerHud = "UI/UIPlayerHud";
			public const string UIQuestsView = "UI/UIQuestsView";
			public const string UIQuestView = "UI/UIQuestView";
			public const string UISettings = "UI/UISettings";
			public const string UISleepView = "UI/UISleepView";
			public const string UISpeechView = "UI/UISpeechView";
			public const string UIStatsView = "UI/UIStatsView";
			public const string UITooltip = "UI/UITooltip";
			public const string UITransitionView = "UI/UITransitionView";
		}

	}
}
