using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

#if FMOD_PRESENT
using FMODUnity;
#endif

namespace PlatformCore.Editor.Tools.Audio
{
	public static class FMODSoundNamesGenerator
	{
		private const string MenuPath = "Tools/Len/PlatformCore/Audio/Generate SoundNames";
		private const string GeneratedFilePath = "Assets/PlatformCore.Generated/Audio/SoundNames.Generated.cs";

		[MenuItem(MenuPath)]
		private static void Generate()
		{
#if FMOD_PRESENT
			var events = EventManager.Events;
			var sb = new StringBuilder();
			sb.AppendLine("// AUTO-GENERATED FILE");
			sb.AppendLine("// Generated by: Tools/Len/PlatformCore/Audio/Generate SoundNames");
			sb.AppendLine("namespace PlatformCore.Services.Audio");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static class SoundNames");
			sb.AppendLine("\t{");

			var count = 0;
			foreach (var keyValuePair in events)
			{
				var path = keyValuePair.Path;
				var fieldName = PathToFieldName(path);
				sb.AppendLine($"\t\tpublic const string {fieldName} = \"{EscapeString(path)}\";");
				count++;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			var directoryPath = Path.GetDirectoryName(GeneratedFilePath);
			if (!string.IsNullOrEmpty(directoryPath))
			{
				Directory.CreateDirectory(directoryPath);
			}

			File.WriteAllText(GeneratedFilePath, sb.ToString(), Encoding.UTF8);
			AssetDatabase.Refresh();
			Debug.Log($"[FMODSoundNamesGenerator] Generated {count} events at '{GeneratedFilePath}'.");
#else
			Debug.LogWarning("[FMODSoundNamesGenerator] FMOD is not installed. Add FMOD and define FMOD_PRESENT to enable generation.");
#endif
		}

		private static string PathToFieldName(string path)
		{
			var lastSlashIndex = path.LastIndexOf('/');
			if (lastSlashIndex >= 0)
			{
				path = path.Substring(lastSlashIndex + 1);
			}

			var sb = new StringBuilder(path.Length);
			for (var i = 0; i < path.Length; i++)
			{
				var c = path[i];
				if (char.IsLetterOrDigit(c) || c == '_')
				{
					sb.Append(c);
				}
				else
				{
					sb.Append('_');
				}
			}

			if (sb.Length == 0)
			{
				return "Event";
			}

			if (char.IsDigit(sb[0]))
			{
				sb.Insert(0, '_');
			}

			return sb.ToString();
		}

		private static string EscapeString(string value)
		{
			return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
		}
	}
}
