using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace PlatformCore.Editor.Tools.Audio
{
	public static class FMODSoundNamesGenerator
	{
		private const string MenuPath = "Len/Audio/Generate SoundNames";
		private const string GeneratedFilePath = "Assets/_Project/Code/Audio/SoundNames.Generated.cs";

		[MenuItem(MenuPath)]
		private static void Generate()
		{
			if (!TryGetEventPaths(out var eventPaths, out var reason))
			{
				Debug.LogWarning($"[FMODSoundNamesGenerator] FMOD events are unavailable. {reason}");
				return;
			}

			var sb = new StringBuilder();
			sb.AppendLine("// AUTO-GENERATED FILE");
			sb.AppendLine("// Generated by: Len/Audio/Generate SoundNames");
			sb.AppendLine("namespace PlatformCore.Services.Audio");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static class SoundNames");
			sb.AppendLine("\t{");

			var count = 0;
			foreach (var path in eventPaths)
			{
				var fieldName = PathToFieldName(path);
				sb.AppendLine($"\t\tpublic const string {fieldName} = \"{EscapeString(path)}\";");
				count++;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			var directoryPath = Path.GetDirectoryName(GeneratedFilePath);
			if (!string.IsNullOrEmpty(directoryPath))
			{
				Directory.CreateDirectory(directoryPath);
			}

			File.WriteAllText(GeneratedFilePath, sb.ToString(), Encoding.UTF8);
			AssetDatabase.Refresh();
			Debug.Log($"[FMODSoundNamesGenerator] Generated {count} events at '{GeneratedFilePath}'.");
		}

		private static bool TryGetEventPaths(out string[] eventPaths, out string reason)
		{
			eventPaths = Array.Empty<string>();
			reason = string.Empty;

			var eventManagerType = Type.GetType("FMODUnity.EventManager, FMODUnityEditor");
			if (eventManagerType == null)
			{
				reason = "FMODUnityEditor assembly not found.";
				return false;
			}

			var eventsProperty = eventManagerType.GetProperty("Events", BindingFlags.Public | BindingFlags.Static);
			if (eventsProperty == null)
			{
				reason = "FMOD EventManager.Events property is missing.";
				return false;
			}

			if (eventsProperty.GetValue(null) is not IEnumerable events)
			{
				reason = "FMOD EventManager.Events is not available yet.";
				return false;
			}

			var result = new List<string>();
			foreach (var eventRef in events)
			{
				var path = GetEventPath(eventRef);
				if (string.IsNullOrEmpty(path))
				{
					continue;
				}

				result.Add(path);
			}

			eventPaths = result.ToArray();
			return true;
		}

		private static string GetEventPath(object eventRef)
		{
			if (eventRef == null)
			{
				return null;
			}

			var eventRefType = eventRef.GetType();

			var pathField = eventRefType.GetField("Path", BindingFlags.Public | BindingFlags.Instance);
			if (pathField != null)
			{
				return pathField.GetValue(eventRef) as string;
			}

			return null;
		}

		private static string PathToFieldName(string path)
		{
			var lastSlashIndex = path.LastIndexOf('/');
			if (lastSlashIndex >= 0)
			{
				path = path.Substring(lastSlashIndex + 1);
			}

			var sb = new StringBuilder(path.Length);
			for (var i = 0; i < path.Length; i++)
			{
				var c = path[i];
				if (char.IsLetterOrDigit(c) || c == '_')
				{
					sb.Append(c);
				}
				else
				{
					sb.Append('_');
				}
			}

			if (sb.Length == 0)
			{
				return "Event";
			}

			if (char.IsDigit(sb[0]))
			{
				sb.Insert(0, '_');
			}

			return sb.ToString();
		}

		private static string EscapeString(string value)
		{
			return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
		}
	}
}
