using System.IO;
using System.Text;
using UnityEditor;

namespace PlatformCore.Editor.Tools.Scenes
{
	public static class ScenesMenuGenerator
	{
		private const string GeneratedFilePath = "Assets/Editor/Tools/Scenes/PlatformCoreGeneratedScenesMenu.cs";
		private const string MenuRoot = "Len/Scenes";

		[MenuItem(MenuRoot + "/Refresh Menu")]
		private static void Generate()
		{
			var scenes = EditorBuildSettings.scenes;
			var sb = new StringBuilder();
			sb.AppendLine("// AUTO-GENERATED FILE");
			sb.AppendLine("// Generated by: Len/Scenes/Refresh Menu");
			sb.AppendLine("using UnityEditor;");
			sb.AppendLine("using UnityEditor.SceneManagement;");
			sb.AppendLine();
			sb.AppendLine("namespace PlatformCore.Editor.Tools.Scenes");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static class PlatformCoreGeneratedScenesMenu");
			sb.AppendLine("\t{");

			var order = 100;
			for (var i = 0; i < scenes.Length; i++)
			{
				var scene = scenes[i];
				if (!scene.enabled)
				{
					continue;
				}

				var path = scene.path;
				var name = Path.GetFileNameWithoutExtension(path);
				var safeName = SanitizeMethodName(name + "_" + i);
				var menuName = EscapeString(name);
				var escapedPath = EscapeString(path);

				sb.AppendLine($"\t\t[MenuItem(\"{MenuRoot}/{menuName}\", false, {order})]");
				sb.AppendLine($"\t\tprivate static void Open_{safeName}()");
				sb.AppendLine("\t\t{");
				sb.AppendLine("\t\t\tif (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())");
				sb.AppendLine("\t\t\t{");
				sb.AppendLine($"\t\t\t\tEditorSceneManager.OpenScene(\"{escapedPath}\");");
				sb.AppendLine("\t\t\t}");
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				order++;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			var generatedDirectory = Path.GetDirectoryName(GeneratedFilePath);
			if (!string.IsNullOrEmpty(generatedDirectory) && !Directory.Exists(generatedDirectory))
			{
				Directory.CreateDirectory(generatedDirectory);
			}

			File.WriteAllText(GeneratedFilePath, sb.ToString(), Encoding.UTF8);
			AssetDatabase.Refresh();
		}

		private static string SanitizeMethodName(string name)
		{
			var sb = new StringBuilder(name.Length);
			for (var i = 0; i < name.Length; i++)
			{
				var c = name[i];
				if (char.IsLetterOrDigit(c) || c == '_')
				{
					sb.Append(c);
				}
				else
				{
					sb.Append('_');
				}
			}

			if (sb.Length == 0)
			{
				return "Scene";
			}

			if (char.IsDigit(sb[0]))
			{
				sb.Insert(0, '_');
			}

			return sb.ToString();
		}

		private static string EscapeString(string value)
		{
			return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
		}
	}
}
