using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace PlatformCore.Editor.Tools.Resources
{
	public static class ResourcePathsGenerator
	{
		private const string ResourcesRootPath = "Assets/Resources";
		private const string GeneratedFilePath = "Assets/PlatformCore.Generated/ResourcePaths.Generated.cs";
		private const string MenuPath = "Len/Resources/Generate ResourcePaths";

		[MenuItem(MenuPath)]
		private static void Generate()
		{
			if (!Directory.Exists(ResourcesRootPath))
			{
				Debug.LogWarning($"[ResourcePathsGenerator] '{ResourcesRootPath}' was not found.");
				return;
			}

			var assetGuids = AssetDatabase.FindAssets(string.Empty, new[] { ResourcesRootPath });
			var paths = new List<string>();

			for (var i = 0; i < assetGuids.Length; i++)
			{
				var path = AssetDatabase.GUIDToAssetPath(assetGuids[i]);
				if (string.IsNullOrEmpty(path))
				{
					continue;
				}

				if (AssetDatabase.IsValidFolder(path))
				{
					continue;
				}

				if (path.EndsWith(".meta", StringComparison.OrdinalIgnoreCase))
				{
					continue;
				}

				if (!path.StartsWith(ResourcesRootPath + "/", StringComparison.Ordinal))
				{
					continue;
				}

				var relativePath = path.Substring(ResourcesRootPath.Length + 1);
				relativePath = Path.ChangeExtension(relativePath, null);
				if (string.IsNullOrWhiteSpace(relativePath))
				{
					continue;
				}

				paths.Add(relativePath.Replace('\\', '/'));
			}

			paths.Sort(StringComparer.Ordinal);
			WriteGeneratedFile(paths);
			AssetDatabase.Refresh();
			Debug.Log($"[ResourcePathsGenerator] Generated {paths.Count} entries at '{GeneratedFilePath}'.");
		}

		private static void WriteGeneratedFile(List<string> paths)
		{
			var directoryPath = Path.GetDirectoryName(GeneratedFilePath);
			if (!string.IsNullOrEmpty(directoryPath))
			{
				Directory.CreateDirectory(directoryPath);
			}

			var sb = new StringBuilder();
			sb.AppendLine("// AUTO-GENERATED FILE");
			sb.AppendLine("// Generated by: Len/Resources/Generate ResourcePaths");
			sb.AppendLine();
			sb.AppendLine("namespace PlatformCore.Services.Factory");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static partial class ResourcePaths");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tpublic static class Project");
			sb.AppendLine("\t\t{");

			var usedFieldNames = new HashSet<string>(StringComparer.Ordinal);
			for (var i = 0; i < paths.Count; i++)
			{
				var path = paths[i];
				var fieldName = CreateUniqueFieldName(path, usedFieldNames);
				sb.AppendLine($"\t\t\tpublic const string {fieldName} = \"{EscapeString(path)}\";");
			}

			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.AppendLine("}");

			File.WriteAllText(GeneratedFilePath, sb.ToString(), Encoding.UTF8);
		}

		private static string CreateFieldName(string path)
		{
			var sb = new StringBuilder(path.Length);
			for (var i = 0; i < path.Length; i++)
			{
				var c = path[i];
				if (char.IsLetterOrDigit(c))
				{
					sb.Append(c);
				}
				else
				{
					sb.Append('_');
				}
			}

			if (sb.Length == 0)
			{
				return "Entry";
			}

			if (char.IsDigit(sb[0]))
			{
				sb.Insert(0, '_');
			}

			return sb.ToString();
		}

		private static string CreateUniqueFieldName(string path, HashSet<string> usedFieldNames)
		{
			var baseName = CreateFieldName(path);
			var uniqueName = baseName;
			var suffix = 1;

			while (!usedFieldNames.Add(uniqueName))
			{
				uniqueName = baseName + "_" + suffix;
				suffix++;
			}

			return uniqueName;
		}

		private static string EscapeString(string value)
		{
			return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
		}
	}
}
