using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using PlatformCore.Services.Factory;
using UnityEditor;
using UnityEngine;

namespace PlatformCore.Editor.Tools.Resources
{
	public static class ResourcePathsGenerator
	{
		private const string ResourcesRootPath = "Assets/Resources";
		private const string GeneratedFilePath = "Assets/PlatformCore.Generated/ResourcePaths.Generated.cs";
		private const string MenuPath = "Len/Resources/Generate ResourcePaths";

		[MenuItem(MenuPath)]
		private static void Generate()
		{
			if (!Directory.Exists(ResourcesRootPath))
			{
				Debug.LogWarning($"[ResourcePathsGenerator] '{ResourcesRootPath}' was not found.");
				return;
			}

			var assetGuids = AssetDatabase.FindAssets(string.Empty, new[] { ResourcesRootPath });
			var platformOwnedPaths = CollectPlatformOwnedPaths();
			var paths = new List<string>();
			var uniquePaths = new HashSet<string>(StringComparer.Ordinal);
			var skippedPlatformOwnedCount = 0;

			for (var i = 0; i < assetGuids.Length; i++)
			{
				var path = AssetDatabase.GUIDToAssetPath(assetGuids[i]);
				if (string.IsNullOrEmpty(path))
				{
					continue;
				}

				if (AssetDatabase.IsValidFolder(path))
				{
					continue;
				}

				if (path.EndsWith(".meta", StringComparison.OrdinalIgnoreCase))
				{
					continue;
				}

				if (!path.StartsWith(ResourcesRootPath + "/", StringComparison.Ordinal))
				{
					continue;
				}

				var relativePath = path.Substring(ResourcesRootPath.Length + 1);
				relativePath = Path.ChangeExtension(relativePath, null);
				if (string.IsNullOrWhiteSpace(relativePath))
				{
					continue;
				}

				relativePath = relativePath.Replace('\\', '/');
				if (!uniquePaths.Add(relativePath))
				{
					continue;
				}

				if (platformOwnedPaths.Contains(relativePath))
				{
					skippedPlatformOwnedCount++;
					continue;
				}

				paths.Add(relativePath);
			}

			paths.Sort(StringComparer.Ordinal);
			WriteGeneratedFile(paths);
			AssetDatabase.Refresh();
			Debug.Log($"[ResourcePathsGenerator] Generated {paths.Count} entries at '{GeneratedFilePath}'. Skipped {skippedPlatformOwnedCount} platform-owned entries.");
		}

		private static void WriteGeneratedFile(List<string> paths)
		{
			var directoryPath = Path.GetDirectoryName(GeneratedFilePath);
			if (!string.IsNullOrEmpty(directoryPath))
			{
				Directory.CreateDirectory(directoryPath);
			}

			var sb = new StringBuilder();
			sb.AppendLine("// AUTO-GENERATED FILE");
			sb.AppendLine("// Generated by: Len/Resources/Generate ResourcePaths");
			sb.AppendLine();
			sb.AppendLine("namespace Project.Infrastructure");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static class ProjectResourcePaths");
			sb.AppendLine("\t{");

			var usedFieldNames = new HashSet<string>(StringComparer.Ordinal);
			for (var i = 0; i < paths.Count; i++)
			{
				var path = paths[i];
				var fieldName = CreateUniqueFieldName(path, usedFieldNames);
				sb.AppendLine($"\t\tpublic const string {fieldName} = \"{EscapeString(path)}\";");
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			File.WriteAllText(GeneratedFilePath, sb.ToString(), Encoding.UTF8);
		}

		private static string CreateFieldName(string path)
		{
			var sb = new StringBuilder(path.Length);
			for (var i = 0; i < path.Length; i++)
			{
				var c = path[i];
				if (char.IsLetterOrDigit(c))
				{
					sb.Append(c);
				}
				else
				{
					sb.Append('_');
				}
			}

			if (sb.Length == 0)
			{
				return "Entry";
			}

			if (char.IsDigit(sb[0]))
			{
				sb.Insert(0, '_');
			}

			return sb.ToString();
		}

		private static string CreateUniqueFieldName(string path, HashSet<string> usedFieldNames)
		{
			var baseName = CreateFieldName(path);
			var uniqueName = baseName;
			var suffix = 1;

			while (!usedFieldNames.Add(uniqueName))
			{
				uniqueName = baseName + "_" + suffix;
				suffix++;
			}

			return uniqueName;
		}

		private static string EscapeString(string value)
		{
			return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
		}

		private static HashSet<string> CollectPlatformOwnedPaths()
		{
			var result = new HashSet<string>(StringComparer.Ordinal);
			CollectConstantStringValues(typeof(ResourcePaths.Platform), result);
			return result;
		}

		private static void CollectConstantStringValues(Type type, HashSet<string> values)
		{
			var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.FlattenHierarchy);
			for (var i = 0; i < fields.Length; i++)
			{
				var field = fields[i];
				if (!field.IsLiteral || field.IsInitOnly || field.FieldType != typeof(string))
				{
					continue;
				}

				var value = field.GetRawConstantValue() as string;
				if (string.IsNullOrWhiteSpace(value))
				{
					continue;
				}

				values.Add(value.Replace('\\', '/'));
			}

			var nestedTypes = type.GetNestedTypes(BindingFlags.Public | BindingFlags.NonPublic);
			for (var i = 0; i < nestedTypes.Length; i++)
			{
				CollectConstantStringValues(nestedTypes[i], values);
			}
		}
	}
}
